baseURL = "https://www.omiranda.dev"
# website title
title = "Osvaldo Miranda"
# Languages config section
defaultContentLanguage = "en"
# whether to use git commit log
enableGitInfo = true

[module]
  [[module.imports]]
    # shortcodes
    path = "github.com/Quiroptero/hugo-shortcodes"
  [[module.imports]]
    # customizations on base theme
    path = "github.com/Quiroptero/hugo-theme-loveit-custom"
  [[module.imports]]
    # site theme
    path = "github.com/dillonzq/LoveIt"

# Author config
[author]
  name = "Osvaldo Miranda"
  email = ""
  link = "https://omiranda.dev"

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.en.params]
      [languages.en.params.home]
        # Home page profile
        [languages.en.params.home.profile]
          enable = true
          # URL of avatar shown in home page
          avatarURL = "/images/profile.jpg"
          #  title shown in home page (HTML format is supported)
          title = "Osvaldo Miranda"
          # subtitle shown in home page (HTML format is supported)
          subtitle = """
          <p>Writer and coder<br>
          That's pretty much the same thing, but in different languages</p>
          """
          # whether to use typeit animation for subtitle
          typeit = false
          # whether to show social links
          social = true
          #  disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.en.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 5
          #  replaced with hiddenFromHomePage in params.page
          # default behavior when you don't set "hiddenFromHomePage" in front matter
          defaultHiddenFromHomePage = false
    # Menu config
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      name = "posts"
      url = "/posts/"
      # title will be shown when you hover on this menu link
      title = ""
    [[languages.en.menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "tags"
      url = "/tags/"
      title = ""
    [[languages.en.menu.main]]
      weight = 3
      identifier = "about"
      pre = ""
      post = ""
      name = "about"
      url = "/about/"
      title = ""
    [[languages.en.menu.main]]
      weight = 4
      identifier = "blogroll"
      pre = ""
      post = ""
      name = "blogroll"
      url = "/blogroll/"
      title = ""
    [[languages.en.menu.main]]
      weight = 5
      identifier = "stats"
      pre = ""
      post = ""
      name = "stats"
      url = "/stats/"
      title = ""
  [languages.es]
    weight = 2
    languageCode = "es"
    languageName = "Español"
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [languages.es.params]
      [languages.es.params.home]
        # Home page profile
        [languages.es.params.home.profile]
          enable = true
          # URL of avatar shown in home page
          avatarURL = "/images/profile.jpg"
          #  title shown in home page (HTML format is supported)
          title = "Osvaldo Miranda"
          # subtitle shown in home page (HTML format is supported)
          subtitle = """
          <p>Escribo y programo<br>
          (Es la misma cosa, en diferentes lenguajes)</p>
          """
          # whether to use typeit animation for subtitle
          typeit = false
          # whether to show social links
          social = true
          #  disclaimer (HTML format is supported)
          disclaimer = ""
        # Home page posts
        [languages.es.params.home.posts]
          enable = true
          # special amount of posts in each home posts page
          paginate = 5
          #  replaced with hiddenFromHomePage in params.page
          # default behavior when you don't set "hiddenFromHomePage" in front matter
          defaultHiddenFromHomePage = false
    [[languages.es.menu.main]]
      weight = 1
      identifier = "posts"
      pre = ""
      post = ""
      name = "publicaciones"
      url = "/posts/"
      title = ""
    [[languages.es.menu.main]]
      weight = 2
      identifier = "tags"
      pre = ""
      post = ""
      name = "etiquetas"
      url = "/tags/"
      title = ""
    [[languages.es.menu.main]]
      weight = 3
      identifier = "about"
      pre = ""
      post = ""
      name = "acerca de"
      url = "/about/"
      title = ""
    [[languages.es.menu.main]]
      weight = 4
      identifier = "blogroll"
      pre = ""
      post = ""
      name = "blogs que sigo"
      url = "/blogs-que-sigo/"
      title = ""
    [[languages.es.menu.main]]
      weight = 5
      identifier = "stats"
      pre = ""
      post = ""
      name = "estadísticas"
      url = "/stats/"
      title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  gitRepo = "https://github.com/Quiroptero/source.omiranda.dev"
  #  which hash function used for SRI, when empty, no SRI is used
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  #  date format
  dateFormat = "2006-01-02"
  # website title for Open Graph and Twitter Cards
  title = "OMIRANDA.DEV"
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = ""
  # website images for Open Graph and Twitter Cards
  images = ["/logo.png"]

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    #  Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = "OMIRANDA.DEV"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #  whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    #  Custom content (HTML format is supported)
    custom = ''
    #  whether to show Hugo and theme info
    hugo = true
    #  whether to show copyright info
    copyright = true
    #  whether to show the author
    author = true
    # Site creation time
    since = 2022
    # ICP info only in China (HTML format is supported)
    icp = ""
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  #  Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  #  List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  #  App icon config
  [params.app]
    # optional site title override for the app when added to an iOS home screen or Android launcher
    title = "Osvaldo Miranda"
    # whether to omit favicon resource links
    noFavicon = false
    # modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    # Android browser theme color
    themeColor = "#ffffff"
    # Safari mask icon color
    iconColor = "#5bbad5"
    # Windows v8-10 tile color
    tileColor = "#da532c"

  #  Search config
  [params.search]
    enable = false
    # type of search engine ["lunr", "algolia"]
    type = "algolia"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Home page config
  [params.home]
    #  amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/profile.jpg"
      #  title shown in home page (HTML format is supported)
      title = "Osvaldo Miranda"
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      #  disclaimer (HTML format is supported)
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 5
      #  replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    [params.social.Github]
      # weight when arranging icons (the greater the weight, the later the icon is positioned)
      weight = 0
      # your social ID
      id = "Quiroptero"
    [params.social.Linkedin]
      weight = 1
      id = "omiranda-dev"
    [params.social.Telegram]
      weight = 2
      id = "omiranda_dev"
    # Email = "xxxx@xxxx.com"
    RSS = true #

  #  Page global config
  [params.page]
    #  whether to show the author
    showAuthor = false
    #  whether to hide a page from home page
    hiddenFromHomePage = false
    #  whether to hide a page from search results
    hiddenFromSearch = false
    #  whether to enable twemoji
    twemoji = false
    # whether to enable lightgallery
    lightgallery = false
    #  whether to enable the ruby extended syntax
    ruby = false
    #  whether to enable the fraction extended syntax
    fraction = true
    #  whether to enable the fontawesome extended syntax
    fontawesome = true
    # whether to show link to Raw Markdown content of the content
    linkToMarkdown = true
    #  whether to show the full text content in RSS
    rssFullText = false
    #  Table of the contents config
    [params.page.toc]
      # whether to enable the table of the contents
      enable = true
      #  whether to keep the static table of the contents in front of the post
      keepStatic = false
      # whether to make the table of the contents in the sidebar automatically collapsed
      auto = false
    #  KaTeX mathematical formulas
    [params.page.math]
      # https://hugoloveit.com/theme-documentation-content/#mathematical-formula
      enable = true
      #  default inline delimiter is $ ... $ and \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      #  default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX extension copy_tex
      copyTex = true
      # KaTeX extension mhchem
      mhchem = false
    #  Code config
    [params.page.code]
      # whether to show the copy button of the code block
      copy = true
      # the maximum number of lines of displayed code by default
      maxShownLines = 25
    #  Mapbox GL JS config
    [params.page.mapbox]
      # access token of Mapbox GL JS
      accessToken = ""
      # style for the light theme
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # style for the dark theme
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # whether to add NavigationControl
      navigation = true
      # whether to add GeolocateControl
      geolocate = true
      # whether to add ScaleControl
      scale = true
      # whether to add FullscreenControl
      fullscreen = true
    #  social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    #  Comment config
    [params.page.comment]
      enable = false

  #  TypeIt config
  [params.typeit]
    # typing speed between each step (measured in milliseconds)
    speed = 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    # character used for the cursor (HTML format is supported)
    cursorChar = ""
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

  #  Site SEO config
  [params.seo]
    # image URL
    image = ""
    # thumbnail URL
    thumbnailUrl = ""

  #  Analytics config
  [params.analytics]
    enable = false

  #  Cookie consent config
  [params.cookieconsent]
    enable = false

  #  CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""

  #  Compatibility config
  [params.compatibility]
    # whether to use Polyfill.io to be compatible with older browsers
    polyfill = false
    # whether to use object-fit-images to be compatible with older browsers
    objectFit = false

# Markup related config in Hugo
[markup]
  # Syntax Highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
# https://gohugo.io/content-management/urls/#permalinks
[Permalinks]
  # posts = ":year/:month/:title"
  posts = ":slugorfilename"

# Privacy config
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]
