name: Build and deploy to omiranda.dev

on:
  push:
    branches:
      - main
#  schedule:
#    - cron:  "0 10 * * *"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    # https://wiki.ubuntu.com/Releases
    steps:
      - name: Checkout project's default branch
        uses: actions/checkout@v3
        # https://github.com/actions/checkout
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        # https://github.com/peaceiris/actions-hugo
        with:
          hugo-version: "0.101.0"
          extended: true

      - name: Build
        run: hugo --gc --minify --enableGitInfo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # https://github.com/peaceiris/actions-gh-pages
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: Quiroptero/omiranda.dev
          cname: omiranda.dev
          publish_branch: main
          publish_dir: ./public
          commit_message: ${{ github.event.head_commit.message }}
