name: notify-new-posts-telegram

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: true
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          safe_output: false
          # "New posts" are markdown files like content/posts/YYYY/MM/name/index.md
          files: content/posts/**/**/**/index.md
          # Find all files that have changed since the last remote commit on the target branch.
          since_last_remote_commit: true
          output_renamed_files_as_deleted_and_added: true

      - name: Install Python
        if: steps.changed-files.outputs.added_files_count > 0
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"

      - name: Install Python dependencies
        if: steps.changed-files.outputs.added_files_count > 0
        run: |
          python -m pip install --upgrade pip
          python -m pip install fire
          python -m pip install python-frontmatter
          python -m pip install telethon

      - name: Notify of new posts
        if: steps.changed-files.outputs.added_files_count > 0
        env:
          ALL_ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: >
          for file in $ALL_ADDED_FILES;
          do python notify_telegram.py run --filepath $file;
          done
